django/crud_review/crud_review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('students/', include('students.urls')),
    path('admin/', admin.site.urls),
]

django/crud_review/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.index, name='index'), # GET /students/
    path('new/', views.new, name='new'), # GET /students/new/
    # path('create/', views.create, name='create'), => 주소자체에 표현이 들어가서X (자원만 포함해야), 해결: GET과 POST를 합친다
    path('<int:pk>/', views.detail, name='detail'), # GET /students/1/
    path('<int:pk>/edit/', views.edit, name='edit'), # GET, POST /student/1/edit
    # path('<int:pk>/update/', views.update, name='update'), # POST /students/1/update(X)
    path('<int:pk>/delete/', views.delete, name='delete'), # POST /students/1/delete => Restful하진 않지만, 장고는 delete를 지원하지 않음
    path('<int:student_pk>/comments/new/', views.comments_new, name='comments_new'),
    path('<int:student_pk>/comments/<int:pk>/delete', views.comments_delete, name='comments_delete'), # POST /students/1/comments/1/delete
    path('<int:student_pk>/comments/<int:pk>/edit', views.comments_edit, name='comments_edit'),

]

# URL Name
# path('주소/', views.함수, name='이름')
# {% url '이름'%} => /students/이름/가 자동으로 생성
# [장점]
# 1. 주소의 변경이 필요할 때, urls.py에서만 수정해주면 됨
# 2. 마지막 '/'를 빼먹는 실수를 차단할 수 있음

# App Name - 특정 app의 urls.py 자체
# {% url 'app_name:path_name' %}

# RESTful- Rest의 구성요소
# 1. 자원(Resource) - URI: 무엇을 가져올지
# 2. 행위(Verb) - HTTP Method (GET, POST, PUT, DELETE, )
# 3. 표현(Representation) - 자원 + 행위
# ex)
# GET    /users/1 =>user 1번 가져옴
# PUT    /users/1
# DELETE /users/1

django/crud_review/students/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=10)
    age = models.IntegerField() # default, ~이상 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}번째 학생 {self.age}살 {self.name}입니다.'
        
# python manage.py makemigrations >> models.py에 생성한 모델을 migrations파일에
# python manage.py migrate >>migrations폴더에 새로 생긴 파일을 DB에 적용

# python manage.py shell >> 파이썬 터미널(장고의 설정들이 들어있는 터미널)
# from articles.models import Article
# article = Article()
# article.title = ''
# article.content = ''
# article.save()

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    # CASCADE : 1:N에서 1이 삭제되면 N도 삭제
    # PROTECT : 1을 삭제하려 할 때, N이 있으면 삭제 불가능
    # SET_NULL : 1이 삭제가 되면 N의 컬럼에 NULL로 설정
    # DO_NOTHING : 아무것도 하지 않음

    # 1. 1번 학생(1) 가져오기
    # student = Student.objects.get(pk=1)

    # 2. 댓글(N) 생성
    # comment = Comment()
    # comment.content = 'First Comment'
    # comment.student = student
    # comment.student_id = student.pk
    # comment.save()

    # 3. 댓글(N)로 부터 학생(1) 불러오기
    # comment.student => student 인스턴스 자체
    # comment.student.age => 학생 나이
    # comment.student.name => 학생 이름

    # 4. 학생(1)으로부터 댓글(N) 불러오기
    # student.comment_set.all() => comment QuerySet

django/crud_review/students/views.py
from django.shortcuts import render, redirect
from .models import Student, Comment

# Create your views here.
def index(request):
    students = Student.objects.all().order_by('-id')
    context = {
        'students': students,
    }
    return render(request, 'students/index.html', context)

def new(request):
    if request.method == 'POST':
        # student를 생성(create)
        name = request.POST.get('name')
        age = request.POST.get('age')
        student = Student(name=name, age=age)
        student.save()
        return redirect('students:detail', student.pk)
    else: #=> 'GET'
        # new page를 보여줌
        return render(request, 'students/new.html')

# def create(request): => RESTful한 주소를 위해 new로 이동
#     name = request.POST.get('name')
#     age = request.POST.get('age')
#     student = Student.objects.create(name=name, age=age)
#     # return redirect(f'/students/{student.pk}/')
#     return redirect('students:detail', student.pk)

def detail(request, pk):
    # 1. pk에 해당하는 student를 db에서 가져오기
    student = Student.objects.get(id=pk)
    # 1-1. student의 comment를 다 가져오기
    comments = student.comment_set.all()
    # 1-2. student의 comment 개수 
    # comments.count

    context = {
        'student': student,
        'comments': comments,
    }
    return render(request, 'students/detail.html', context)

def delete(request, pk):
    if request.method == 'POST': # GET요청이 들어올 경우 수행x
        student = Student.objects.get(id=pk)
        student.delete()
        # return redirect('/students/')
        return redirect('students:index')

def edit(request, pk):
    student = Student.objects.get(id=pk)

    if request.method == 'POST':        
        student = Student.objects.get(id=pk)
        name = request.POST.get('name')
        age = request.POST.get('age')
        student.name = name
        student.age = age
        student.save()
        return redirect('students:detail', student.pk)

    else:
        context = {
            'student': student,
        }
        return render(request, 'students/edit.html', context)


# def update(request, pk):
#     student = Student.objects.get(id=pk)
#     name = request.POST.get('name')
#     age = request.POST.get('age')

#     student.name = name
#     student.age = age
#     student.save()
#     # return redirect(f'/students/{student.pk}/')
#     return redirect('students:detail', student.pk)

def comments_new(request, student_pk):
    # 1. request에서 데이터 가져오기
    content = request.POST.get('content')
    # 2. Comment 생성
    comment = Comment()
    comment.content = content
    comment.student_id = student_pk
    comment.save()
    # 3. student 상세 페이지로 redirect
    return redirect('students:detail', student_pk)

# POST 요청을 받음
def comments_delete(request, student_pk, pk):
    comment = Comment.objects.get(pk=pk)
    comment.delete()
    return redirect('students:detail', student_pk)

def comments_edit(request, student_pk, pk):
    comment = Comment.objects.get(pk=pk)
    if request.method == 'POST':
        # POST
        # 1. POST로 넘어온 데이터 가져오기
        content = request.POST.get('content')
        # 2. comment에 바꿔 넣기 & 저장
        comment.content = content
        comment.save()
        # 3. 댓글목록 페이지로 redirect
        return redirect('students:detail', student_pk)

    else:
        # GET
        context = {
            'comment': comment,
        }
        return render(request, 'students/comments_edit.html', context)

django/crud_review/students/templates/students/comments_edit.html
{% extends 'base.html' %}
{% block body %}
<h1>Edit Comment</h1>
<form action="" method="POST">
    {% csrf_token %}
    <textarea name="content" id="" cols="30" rows="10" >{{ comment.content }}</textarea>
    <input type="submit">
</form>

{% endblock %}

django/crud_review/students/templates/students/create.html
{% extends 'base.html' %}
{% block body %}
 {{name}}
 {{age}}

<a href="{% url 'students:index' %}">INDEX로</a>

{% endblock %}

django/crud_review/students/templates/students/detail.html
{% extends 'base.html' %}
{% block body %}
 <h1> Detail </h1>
 <h5> 이름: {{student.name}} </h5>
 <h5> 나이: {{student.age}} </h5>

<a href="{% url 'students:index' %}">List</a>
<a href="{% url 'students:edit' student.pk %}">Edit</a>
<!-- a 태그는 POST 요청을 보낼 수 없기 때문에 form 태그를 이용해야한다 -->
<!-- a href="{% url 'students:delete' student.pk %}">Delete</a -->
<form action="{% url 'students:delete' student.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

<hr>
<!-- 댓글의 갯수를 표현하는 1번째 방법(Django DTL) -->
<!-- <h4>댓글 목록 / 댓글 갯수: {{ comments|length }}</h4> -->

<!-- 댓글의 갯수를 표현하는 2번째 방법(Django ORM) -->
<h4>댓글 목록 / 댓글 갯수: {{ comments.count }}</h4>

<ul>
    {% for comment in comments %} <!-- comments: student.comment_set.all -->
    <li>{{ comment.content }}
        <a href="{% url 'students:comments_edit' student.pk comment.pk %}">수정</a>
        <form action="{% url 'students:comments_delete' student.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    </li>
    {% empty %}
    <li> 작성된 댓글이 없습니다:( </li>
    {% endfor %}
</ul>


<!-- Comment 입력창 -->
<form action="{% url 'students:comments_new' student.pk %}" method="POST">
    {% csrf_token %}
    <label for="">Comment: </label><br>
    <textarea name="content" id="" cols="30" rows="5"></textarea>
    <input type="submit">
</form>

{% endblock %}

django/crud_review/students/templates/students/edit.html
{% extends 'base.html' %}
{% block body %}

<h1>Edit Student</h1>

<!-- Form action="/students/{{student.pk}}/update/" method="POST" -->
<!-- Form action="% url 'students:update' student.pk %" method="POST" -->
<Form action="" method="POST">
    {% csrf_token %}
    <label for="">학생이름: </label>
    <input type="text" name="name" value="{{student.name}}"><br>

    <label for="">학생나이: </label>
    <input type="number" name="age" value="{{student.age}}">

    <input type="submit">

</Form>

{% endblock %}

django/crud_review/students/templates/students/index.html
{% extends 'base.html' %}
{% block body %}

<h1> INDEX </h1>

<!-- <a href="/students/new/">New</a> -->
<a href="{% url 'students:new' %}">New</a>

<ol>{% for student in students %}
    <!-- <li><a href="/students/{{student.id}}/">{{ student.name }}</a> </li> -->
    <li><a href="{% url 'students:detail' student.pk %}">{{ student.name }}</a> </li>
    {% endfor %}
</ol>

{% endblock %}

django/crud_review/students/templates/students/new.html
{% extends 'base.html' %}
{% block body %}

<h1> NEW Student </h1>
<!-- form action="% url 'students:create' %" method="POST" -->
<form action="" method="POST"> <!-- action 값이 없으면 자기자신으로 보냄 -->
    {% csrf_token %}
    <label for="">학생이름: </label>
    <input type="text" name="name"><br>

    <label for="">학생나이: </label>
    <input type="number" name="age">

    <input type="submit">

</form>
{% endblock %}

<!-- input*n : input 태그 여러개 한번에 -->