django/pjt01/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    # path('create/', views.create, name='create'),
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    # path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

django/pjt01/pjt01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

django/pjt01/movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50) # 영화명
    title_en = models.CharField(max_length=50, blank=True) # 영화명(영문)
    audience = models.IntegerField(default=0) # 누적 관객수
    open_date = models.DateField(default=timezone.now) # 개봉일
    genre = models.CharField(max_length=50, blank=True) # 장르
    watch_grade = models.CharField(max_length=50, blank=True) # 관람등급
    score = models.FloatField(default=0) # 평점
    poster_url = models.TextField(null=True, blank=True) # 포스터 이미지 URL
    description = models.TextField(null=True, blank=True) # 영화 소개

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'제목:{self.title}, 평점:{self.score}'

django/pjt01/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

# Create your views here.
def index(request):
    movies = Movie.objects.all().order_by('-id')
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def new(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')
        movie = Movie.objects.create(
            title=title,
            title_en=title_en,
            audience=audience,
            open_date=open_date,
            genre=genre,
            watch_grade=watch_grade, 
            score=score,
            poster_url=poster_url,
            description=description
            )
        return redirect('movies:detail', movie.pk)
    else:
        return render(request, 'movies/new.html')


def detail(request, pk):
    movie = Movie.objects.get(id=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


def edit(request, pk):
    movie = Movie.objects.get(id=pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')

        movie.title = title
        movie.title_en = title_en
        movie.audience = audience
        movie.open_date = open_date
        movie.genre = genre
        movie.watch_grade = watch_grade
        movie.score = score
        movie.poster_url = poster_url
        movie.description = description
        movie.save()

        return redirect('movies:detail', movie.pk)
        
    else:
        context = {
            'movie': movie,
        }
        return render(request, 'movies/edit.html', context)


def delete(request, pk):
    if request.method == 'POST':
        movie = Movie.objects.get(id=pk)
        movie.delete()
        return redirect('movies:index')

django/pjt01/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block body %}
<h1> Detail </h1>
<img src="{{ movie.poster_url }}" alt="poster" width="300px">

<ul>
    <li><b> {{ movie.title }} </b></li>
    <li> {{ movie.title_en }} </li>
    <li> {{ movie.audience }} </li>
    <li> {{ movie.open_date }} </li>
    <li> {{ movie.genre }} </li>
    <li> {{ movie.watch_grade }} </li>
    <li> {{ movie.score }} </li>
    <li> {{ movie.description }} </li>
</ul>

<a href="{% url 'movies:index' %}">목록</a>
<a href="{% url 'movies:edit' movie.pk %}">수정</a>

<form action="{% url 'movies:delete' movie.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="delete">
</form>

{% endblock %}

django/pjt01/movies/templates/movies/edit.html
{% extends 'base.html' %}
{% block body %}
<h1>Edit</h1>
<form action="" method="POST">
        {% csrf_token %}
    <table>
        <tr>
            <td><label for="">영화명:</label></td>
            <td><input type="text" name="title" value="{{movie.title}}"></td>
        </tr>
        <tr>
            <td><label for="">영화명(영문):</label></td>
            <td><input type="text" name="title_en" value="{{movie.title_en}}" ></td>
        </tr>
        <tr>
            <td><label for="">누적 관객수:</label></td>
            <td><input type="number" name="audience" value="{{movie.audience}}"></td>
        </tr>
        <tr>
            <td><label for="">개봉일:</label></td>
            <td><input type="date" name="open_date" value="{{ movie.open_date|date:'Y-m-d'}}"></td>
        </tr>
        <tr>
            <td><label for="">장르:</label></td>
            <td><input type="text" name="genre" value="{{movie.genre}}"> </td>
        </tr>
        <tr>
            <td><label for="">관람등급</label></td>
            <td><input type="text" name="watch_grade" value="{{movie.watch_grade}} "></td>
        </tr>
        <tr>
            <td><label for="">평점:</label></td>
            <td><input type="number" name="score" step="0.01" min="0" max="10" value="{{movie.score}}" ></td>
        </tr>
        <tr>
            <td><label for="">포스터 이미지:</label></td>
            <td><input type="text" name="poster_url" value="{{ movie.poster_url }}"></td>
        </tr>
        <tr>
            <td><label for="">영화소개</label></td>
            <td><textarea name="description" cols="30" rows="10">{{ movie.description }}</textarea></td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit"></td>
        </tr>
    </table>    
</form>
{% endblock %}

django/pjt01/movies/templates/movies/index.html
{% extends 'base.html' %}
{% block body %}

<h1> Index </h1>

{% for movie in movies %}
<ul>
    <li><a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a> 평점:{{ movie.score }} </li>
</ul>
{% endfor %}
<a href="{% url 'movies:new' %}">추가</a>

{% endblock %}

django/pjt01/movies/templates/movies/new.html
{% extends 'base.html' %}
{% block body %}
<h1>New</h1>
<form action="" method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <td><label for="">영화명:</label></td>
            <td><input type="text" name="title"></td>
        </tr>
        <tr>
            <td><label for="">영화명(영문):</label></td>
            <td><input type="text" name="title_en"></td>
        </tr>
        <tr>
            <td><label for="">누적 관객수:</label></td>
            <td><input type="number" name="audience"></td>
        </tr>
        <tr>
            <td><label for="">개봉일:</label></td>
            <td><input type="date" name="open_date"></td>
        </tr>
        <tr>
            <td><label for="">장르:</label></td>
            <td><input type="text" name="genre"> </td>
        </tr>
        <tr>
            <td><label for="">관람등급</label></td>
            <td><input type="text" name="watch_grade"></td>
        </tr>
        <tr>
            <td><label for="">평점:</label></td>
            <td><input type="number" name="score" step="0.01" min="0" max="10"></td>
        </tr>
        <tr>
            <td><label for="">포스터 이미지:</label></td>
            <td><input type="text" name="poster_url"></td>
        </tr>
        <tr>
            <td><label for="">영화소개</label></td>
            <td><textarea name="description" cols="30" rows="10"></textarea></td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit"></td>
        </tr>
    </table>    
</form>
{% endblock %}

django/pjt01/pjt01/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>